# Generated by Django 3.1.1 on 2020-09-17 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ballast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('maxVolume', models.DecimalField(decimal_places=2, max_digits=6)),
                ('actualVolume', models.DecimalField(decimal_places=2, max_digits=6)),
                ('isClean', models.BooleanField()),
                ('maxSounding', models.DecimalField(decimal_places=2, max_digits=4)),
                ('LCStart', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('LCEnd', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('TCStart', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('TCEnd', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('VCStart', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('VCEnd', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('flowRate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('flowRateTestDate', models.DateTimeField(blank=True, null=True)),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TransferType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDateTimeUTC', models.DateTimeField()),
                ('startTxt', models.CharField(max_length=20)),
                ('startLat', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('startLong', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('quantityInBallastStart', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stopDateTimeUTC', models.DateTimeField()),
                ('stopTxt', models.CharField(max_length=20)),
                ('stopLat', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('stopLong', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('quantityInBallastStop', models.DecimalField(decimal_places=2, max_digits=6)),
                ('timeZone', models.DecimalField(decimal_places=1, max_digits=3)),
                ('transferredQuantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('isInUseBWTS', models.BooleanField()),
                ('isClean', models.BooleanField()),
                ('unpumpable', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('density', models.DecimalField(decimal_places=5, max_digits=6)),
                ('temperature', models.IntegerField()),
                ('salinity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('ballast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ballast')),
                ('ballastFromTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_ballastFromTo', to='app.ballast')),
                ('transferType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transfertype')),
                ('transferredBy', models.ManyToManyField(to='app.Pump')),
            ],
        ),
    ]
