# Generated by Django 3.1.1 on 2020-09-16 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ballasts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('maxVolume', models.DecimalField(decimal_places=2, max_digits=6)),
                ('maxUllage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('LCStart', models.DecimalField(decimal_places=2, max_digits=5)),
                ('LCEnd', models.DecimalField(decimal_places=2, max_digits=5)),
                ('TCStart', models.DecimalField(decimal_places=2, max_digits=5)),
                ('TCEnd', models.DecimalField(decimal_places=2, max_digits=5)),
                ('VCStart', models.DecimalField(decimal_places=2, max_digits=5)),
                ('VCEnd', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pumps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lastRateTest', models.DateTimeField()),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isClean', models.BooleanField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantity inside')),
                ('unpumpable', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sourceTxt', models.CharField(max_length=20)),
                ('sourceLat', models.DecimalField(decimal_places=6, max_digits=8)),
                ('sourceLong', models.DecimalField(decimal_places=6, max_digits=9)),
                ('salinity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('mixing', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='Mixing Ration')),
                ('ballast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ballasts')),
            ],
        ),
        migrations.CreateModel(
            name='Movements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTimeUTC', models.DateTimeField()),
                ('timeZone', models.DecimalField(decimal_places=1, max_digits=3)),
                ('locationTxT', models.CharField(max_length=20)),
                ('locationLat', models.DecimalField(decimal_places=6, max_digits=8)),
                ('locationLong', models.DecimalField(decimal_places=6, max_digits=9)),
                ('density', models.DecimalField(decimal_places=5, max_digits=6)),
                ('temperature', models.IntegerField()),
                ('salinity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantity transferred')),
                ('distance', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Distance from shore')),
                ('depth', models.IntegerField()),
                ('speed', models.DecimalField(decimal_places=1, max_digits=5)),
                ('isBWTS', models.BooleanField()),
                ('comment', models.CharField(max_length=200)),
                ('ballastFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ballasts')),
                ('ballastTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements_ballastTo', to='app.ballasts')),
                ('pumpUsed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pumps')),
            ],
        ),
    ]
