# Generated by Django 3.1.1 on 2020-09-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ballasts',
            old_name='maxUllage',
            new_name='maxSounding',
        ),
    ]
