# Generated by Django 3.1.1 on 2020-09-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200916_1351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ballasts',
            new_name='Ballast',
        ),
        migrations.RenameModel(
            old_name='Pumps',
            new_name='Pump',
        ),
    ]
